# Generated by Django 6.0.8 on 2026-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Video')),
                ('youtube_url', models.URLField(verbose_name='Enlace de YouTube')),
                ('section_identifier', models.CharField(db_index=True, help_text="Clave única para identificar el video en la interfaz (Ej: 'hero_main', 'hseq_popup').", max_length=100, unique=True, verbose_name='Identificador de Sección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enlace de Video',
                'verbose_name_plural': 'Enlaces de Video',
                'ordering': ['id'],
            },
        ),
    ]
