# Generated by Django 6.0.8 on 2026-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(choices=[(1, 'Juego 1'), (2, 'Juego 2'), (3, 'Juego 3'), (4, 'Juego 4')], db_index=True, verbose_name='ID de Juego')),
                ('score', models.FloatField(verbose_name='Puntaje')),
                ('attempts', models.IntegerField(default=1, verbose_name='Intentos')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Juego',
                'verbose_name_plural': 'Registros de Juego',
                'ordering': ['-created_at'],
            },
        ),
    ]
